llm_max_tokens: 3000
llm_temperature: 0.1
vs_endpoint: one-env-shared-endpoint-3
vs_combined_chunks_table: shm.multimodal.combined_chunks
vs_index_name: shm.multimodal.multimodal_index
score_threshold: 0.1
num_results: 3
retrieval_prompt: >
  You are a maintenance assistant. Use the documents in the context below to answer technical questions about aircraft maintenance on specific pieces of equipment. If you don't know the answer, just say that you don't know, don't try to make up an answer. Keep the answer concise, do not repeat the prompt.

  Use the following pieces of context from existing documents to answer the question at the end:

  {context}

  Question: {question}
  Answer: