# Agent configuration
model:
  endpoint_name: databricks-meta-llama-3-3-70b-instruct
  parameters:
    temperature: 0
    max_tokens: 400
langgraph:  
  streaming: True
retriever:
  endpoint_name: one-env-shared-endpoint-3
  index_name: shm.multimodal.multimodal_index
  embedding_model: databricks-gte-large-en
  parameters:
    k: 3
    query_type: ann
  schema:
    chunk_text: content
    document_uri: url
    primary_key: id
    other_columns: 
    - filename
    - type
  chunk_template: 'Passage: {chunk_text}\n'
mlflow:
  experiment_location: "/Users/marshall.carter@databricks.com/langgraph_models"
  uc_model: main.default.mlc_langgraph_model
